import React,{useEffect,useState} from 'react'
import {edge,publicMedia,supabase} from './supabase'

const fields=[['groom','신랑 이름'],['bride','신부 이름'],['date','날짜'],['date_display','날짜 표시'],['time','시간'],['venue','예식장'],['address','주소'],['map_url','약도 링크'],['groom_parents','신랑측 부모 표기'],['bride_parents','신부측 부모 표기'],['invitation_headline','초대글 제목'],['invitation_body','초대글 본문'],['additional_info','기타 안내'],['groom_accounts','신랑측 계좌'],['bride_accounts','신부측 계좌'],['short1_title','Shorts 1 제목'],['short1_text','Shorts 1 문구'],['short2_title','Shorts 2 제목'],['short2_text','Shorts 2 문구'],['main_title','메인 제목']]
const textareas=new Set(['invitation_headline','invitation_body','additional_info','groom_accounts','bride_accounts','short1_text','short2_text'])

export default function Admin(){
  const [setup,setSetup]=useState(null),[token,setToken]=useState(localStorage.getItem('wedding_admin_token')||''),[data,setData]=useState(null),[msg,setMsg]=useState(''),[ogVersion,setOgVersion]=useState(Date.now())
  useEffect(()=>{(async()=>{try{const s=await edge('wedding-admin-youtube',{action:'status'});setSetup(s.setup_complete);if(s.setup_complete&&token)await load(token)}catch{setMsg('관리자 서버 연결을 확인해 주세요.')}})()},[])
  async function load(t=token){try{setData(await edge('wedding-admin-youtube',{action:'get'},t))}catch{localStorage.removeItem('wedding_admin_token');setToken('');setData(null)}}
  async function auth(e,action){e.preventDefault();const fd=new FormData(e.currentTarget),password=String(fd.get('password')||''),setup_code=String(fd.get('setup_code')||'');setMsg('처리 중...');try{const d=await edge('wedding-admin-youtube',{action,password,setup_code});localStorage.setItem('wedding_admin_token',d.token);setToken(d.token);setSetup(true);setMsg('');await load(d.token)}catch{setMsg(action==='setup_password'?'비밀번호 설정에 실패했어요.':'비밀번호가 맞지 않아요.')}}
  if(setup===null)return <div className="admin-shell"><div className="admin-login-card">불러오는 중...</div></div>
  if(!setup)return <div className="admin-shell"><form className="admin-login-card" onSubmit={e=>auth(e,'setup_password')}><span className="admin-badge">OWNER SETUP</span><h1>관리자 비밀번호 만들기</h1><p>처음 한 번만 설정됩니다. 아래 일회용 설정 코드와 새 비밀번호를 입력해 주세요.</p><input name="setup_code" placeholder="일회용 설정 코드" required autoComplete="off"/><input name="password" type="password" minLength="8" required autoComplete="new-password" placeholder="새 관리자 비밀번호"/><button>비밀번호 설정</button><p className="admin-message">{msg}</p></form></div>
  if(!token||!data)return <div className="admin-shell"><form className="admin-login-card" onSubmit={e=>auth(e,'login')}><span className="admin-badge">OWNER</span><h1>청첩장 편집</h1><p>관리자 비밀번호를 입력해 주세요.</p><input name="password" type="password" minLength="8" required/><button>로그인</button><p className="admin-message">{msg}</p></form></div>
  const c=data.content||{},media=data.media||[]
  async function save(e){e.preventDefault();const fd=new FormData(e.currentTarget),content={};for(const [k] of fields)content[k]=String(fd.get(k)||'');setMsg('저장 중...');try{await edge('wedding-admin-youtube',{action:'save_content',content},token);setMsg('저장했습니다.');await load()}catch{setMsg('저장에 실패했어요.')}}
  async function upload(role,file,caption=''){if(!file)return;const kind=file.type.startsWith('video/')?'video':'image',max=kind==='video'?80*1024*1024:12*1024*1024;if(file.size>max){setMsg(kind==='video'?'영상은 80MB 이하로 올려주세요.':'사진은 12MB 이하로 올려주세요.');return}setMsg('업로드 중...');try{const u=await edge('wedding-admin-youtube',{action:'create_upload',role,kind,content_type:file.type,file_name:file.name},token);const {error}=await supabase.storage.from('wedding-media').uploadToSignedUrl(u.path,u.token,file,{contentType:file.type});if(error)throw error;await edge('wedding-admin-youtube',{action:'register_media',role,kind,object_path:u.path,caption},token);setMsg('업로드 완료');await load()}catch{setMsg('업로드에 실패했어요.')}}
  async function uploadOg(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setMsg('공유 썸네일은 JPG, PNG, WebP만 올릴 수 있어요.');return}if(file.size>12*1024*1024){setMsg('공유 썸네일은 12MB 이하로 올려주세요.');return}setMsg('공유 썸네일 업로드 중...');try{const u=await edge('wedding-admin-youtube',{action:'create_og_upload',content_type:file.type,file_name:file.name},token);const {error}=await supabase.storage.from('wedding-media').uploadToSignedUrl(u.path,u.token,file,{contentType:file.type});if(error)throw error;setOgVersion(Date.now());setMsg('공유 썸네일을 교체했습니다. 카카오톡 등에서는 기존 미리보기가 잠시 캐시될 수 있어요.')}catch{setMsg('공유 썸네일 업로드에 실패했어요.')}}
  async function del(id){if(!confirm('이 파일을 삭제할까요?'))return;await edge('wedding-admin-youtube',{action:'delete_media',id},token);await load()}
  async function delGuest(id){if(!confirm('이 방명록을 삭제할까요?'))return;await edge('wedding-admin-youtube',{action:'delete_guestbook',id},token);await load()}
  function logout(){localStorage.removeItem('wedding_admin_token');setToken('');setData(null)}
  return <div className="admin-shell"><div className="admin-topbar"><div><span className="admin-badge">OWNER EDITOR</span><h1>범수 ♥ 서영 청첩장</h1></div><div className="admin-actions"><a href="/">하객 화면</a><button onClick={logout}>로그아웃</button></div></div><p className="admin-toast">{msg}</p>
    <form className="admin-panel" onSubmit={save}><h2>기본 정보와 문구</h2><div className="admin-grid">{fields.map(([k,l])=><label key={k} className={textareas.has(k)?'wide':''}><span>{l}</span>{textareas.has(k)?<textarea name={k} defaultValue={c[k]||''}/>:<input name={k} defaultValue={c[k]||''}/>}</label>)}</div><button className="primary">전체 내용 저장</button></form>
    <section className="admin-panel"><h2>사진과 영상</h2><div className="og-upload-card"><div className="og-upload-copy"><strong>공유 썸네일</strong><p>카카오톡·문자·메신저에서 청첩장 링크와 함께 보이는 대표 이미지입니다. 가로형 1200 × 630px를 권장합니다.</p><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>uploadOg(e.target.files?.[0])}/></div><div className="og-preview"><span>현재 미리보기</span><img src={publicMedia('defaults/og-cover.png')+'?v='+ogVersion} alt="공유 썸네일 미리보기"/></div></div><div className="upload-grid">{[['hero','대표 사진','image/*'],['short1','Shorts 1','image/*'],['short2','Shorts 2','image/*'],['video','메인 영상','video/mp4,video/webm,video/quicktime']].map(([r,l,a])=><label className="upload-box" key={r}><strong>{l}</strong><input type="file" accept={a} onChange={e=>upload(r,e.target.files?.[0])}/></label>)}</div><label className="upload-box gallery-upload"><strong>사진첩 추가</strong><input type="file" accept="image/*" onChange={e=>upload('gallery',e.target.files?.[0],prompt('사진 설명을 입력해 주세요')||'우리의 사진')}/></label><div className="admin-media-grid">{media.map(m=><figure key={m.id}>{m.kind==='video'?<video src={publicMedia(m.object_path)} controls/>:<img src={publicMedia(m.object_path)}/>}<figcaption><span>{m.role} {m.caption}</span><button onClick={()=>del(m.id)}>삭제</button></figcaption></figure>)}</div></section>
    <section className="admin-panel"><h2>RSVP</h2><div className="admin-list">{(data.rsvp||[]).map(x=><div key={x.id}><strong>{x.name}</strong><span>{x.side} · {x.attendance} · {x.guests}명</span><p>{x.note}</p></div>)}</div></section>
    <section className="admin-panel"><h2>방명록 관리</h2><div className="admin-list">{(data.guestbook||[]).map(x=><div key={x.id}><strong>{x.name}</strong><p>{x.message}</p><button onClick={()=>delGuest(x.id)}>삭제</button></div>)}</div></section>
  </div>
}
