import React,{useEffect,useMemo,useRef,useState} from 'react'
import {edge,publicMedia,supabase} from './supabase'

const FALLBACK={groom:'전범수',bride:'최서영',date:'2027-12-11',date_display:'2027년 12월 11일 토요일',time:'오후 3시',venue:'예식 장소 추후 안내',address:'',map_url:'',groom_parents:'전용섭 · 손미연의 장남',bride_parents:'최영민 · 배은희의 장녀',invitation_headline:'결혼은 마라톤? 아니요,\n저희는 릴레이로 뛰려 합니다.',invitation_body:'때론 달리고, 때론 쉬고,\n서로의 바통을 꼭 잡고 달릴 거예요.\n\n완벽하지 않아도 괜찮아요,\n같이 웃고 울며 성장할 테니까요.\n\n그 시작점에 여러분의 따뜻한 응원이 큰 힘이 됩니다.\n지켜봐 주세요, 그리고 함께 축하해 주세요!\n우리의 작은 무대에 여러분을 초대합니다.',additional_info:'',groom_accounts:'',bride_accounts:'',short1_title:'게임에서 시작된 우리',short1_text:'친구의 친구로 만나, 어느새 가장 가까운 사이가 됐어요 💜',short2_title:'함께라서 기대되는 내일',short2_text:'경주에서 오사카까지, 우리의 추억은 계속 쌓이는 중 💜',main_title:'전범수 ♥ 최서영 모바일 청첩장'}
const defaults={hero:publicMedia('defaults/hero.png'),short1:publicMedia('defaults/short-first.png'),short2:publicMedia('defaults/short-gyeongju.png'),osaka:publicMedia('defaults/short-osaka.png')}
const url=m=>m?publicMedia(m.object_path):null
const lines=v=>(v||'').split('\n').map(x=>x.trim()).filter(Boolean)

function SvgIcon({children,size=24}){return <svg aria-hidden="true" viewBox="0 0 24 24" width={size} height={size} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{children}</svg>}
function BellIcon(){return <SvgIcon size={27}><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></SvgIcon>}
function SearchIcon(){return <SvgIcon size={27}><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></SvgIcon>}
function CompassIcon(){return <SvgIcon size={26}><circle cx="12" cy="12" r="9"/><path d="m15.2 8.8-2.1 4.3-4.3 2.1 2.1-4.3 4.3-2.1Z"/></SvgIcon>}
function HomeIcon(){return <SvgIcon size={27}><path d="m3 11 9-7 9 7v9H6v-9"/><path d="M9 20v-6h6v6"/></SvgIcon>}
function ShortsIcon(){return <svg aria-hidden="true" width="28" height="28" viewBox="0 0 28 28"><path d="M17.6 2.7c2.4-1.2 5.4-.2 6.6 2.2 1.1 2.2.4 4.8-1.7 6.1l-3.7 2.2 3.4 1.9c2.4 1.4 3.2 4.4 1.8 6.8-1.4 2.3-4.4 3.1-6.7 1.8L7.9 18.3c-2.5-1.4-3.3-4.6-1.8-7 1.4-2.2 4.1-3 6.4-1.9l3.1 1.6-2.5-1.5c-2.4-1.4-3.2-4.5-1.7-6.9 1.3-2.2 4.1-3 6.2-1.9Z" fill="currentColor"/><path d="m12 10.7 7 3.8-7 3.8v-7.6Z" fill="white"/></svg>}
function PlusIcon(){return <SvgIcon size={30}><path d="M12 5v14M5 12h14"/></SvgIcon>}
function SubscriptionsIcon(){return <SvgIcon size={27}><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 11l6 3-6 3v-6ZM7 3h10"/></SvgIcon>}
function UserIcon(){return <SvgIcon size={27}><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></SvgIcon>}
function CalendarIcon({size=19}){return <SvgIcon size={size}><rect x="4" y="5" width="16" height="15" rx="2.5"/><path d="M8 3v4M16 3v4M4 10h16"/><path d="M8 14h2M14 14h2M8 17h2"/></SvgIcon>}
function LocationIcon({size=19}){return <SvgIcon size={size}><path d="M12 21s6-5.2 6-11a6 6 0 1 0-12 0c0 5.8 6 11 6 11Z"/><circle cx="12" cy="10" r="2.2"/></SvgIcon>}

export default function App(){
  const [content,setContent]=useState(FALLBACK),[media,setMedia]=useState([]),[comments,setComments]=useState([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0),[light,setLight]=useState(null),[rsvpOpen,setRsvpOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false),[gstatus,setGstatus]=useState(''),[rstatus,setRstatus]=useState(''),[pullDistance,setPullDistance]=useState(0),[showTop,setShowTop]=useState(false)
  const refs={home:useRef(null),story:useRef(null),wedding:useRef(null),gallery:useRef(null),guestbook:useRef(null),gift:useRef(null)}
  const galleryRail=useRef(null)
  const galleryDrag=useRef({down:false,startX:0,scrollLeft:0,moved:false})
  const pullStart=useRef({active:false,x:0,y:0})
  const lightSwipe=useRef({active:false,x:0,y:0,pointerId:null})
  const [active,setActive]=useState('home')
  useEffect(()=>{(async()=>{const [{data:c},{data:m}]=await Promise.all([supabase.from('wedding_content').select('*').eq('id',1).single(),supabase.from('wedding_media').select('*').order('created_at',{ascending:false})]);if(c)setContent(c);if(m)setMedia(m);await loadComments(1)})()},[])
  useEffect(()=>{const onScroll=()=>setShowTop(window.scrollY>520);onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[])
  async function loadComments(p){const from=(p-1)*5;const {data,count}=await supabase.from('guestbook').select('id,name,message,created_at,updated_at',{count:'exact'}).order('created_at',{ascending:false}).range(from,from+4);setComments(data||[]);setTotal(count||0);setPage(p);setPages(Math.max(1,Math.ceil((count||0)/5)))}
  const role=r=>media.find(x=>x.role===r)
  const hero=url(role('hero'))||defaults.hero,short1=url(role('short1'))||defaults.short1,short2=url(role('short2'))||defaults.short2,video=role('video')
  const gallery=useMemo(()=>{const g=media.filter(x=>x.role==='gallery');return g.length?g.map(x=>({src:url(x),caption:x.caption||'우리의 사진'})):[{src:hero,caption:'2027 · 우리 결혼합니다'},{src:short1,caption:'우리의 시작'},{src:short2,caption:'경주'},{src:defaults.osaka,caption:'오사카'}]},[media,hero,short1,short2])
  const go=k=>{setActive(k);refs[k].current?.scrollIntoView({behavior:'smooth',block:'start'})}
  const goTop=()=>{setActive('home');window.scrollTo({top:0,behavior:'smooth'})}
  const galleryStep=dir=>{const el=galleryRail.current;if(!el)return;el.scrollBy({left:dir*Math.max(250,el.clientWidth*.84),behavior:'smooth'})}
  const galleryPointerDown=e=>{if(e.pointerType!=='mouse'||e.button!==0)return;const el=galleryRail.current;if(!el)return;galleryDrag.current={down:true,startX:e.clientX,scrollLeft:el.scrollLeft,moved:false};el.setPointerCapture?.(e.pointerId)}
  const galleryPointerMove=e=>{const d=galleryDrag.current,el=galleryRail.current;if(!d.down||!el)return;const dx=e.clientX-d.startX;if(Math.abs(dx)>5)d.moved=true;el.scrollLeft=d.scrollLeft-dx}
  const galleryPointerUp=e=>{const el=galleryRail.current;galleryDrag.current.down=false;el?.releasePointerCapture?.(e.pointerId)}
  const pullTouchStart=e=>{if(window.scrollY>0||light||rsvpOpen||profileOpen)return;const t=e.touches?.[0];if(!t)return;pullStart.current={active:true,x:t.clientX,y:t.clientY}}
  const pullTouchMove=e=>{const t=e.touches?.[0],p=pullStart.current;if(!p.active||!t||window.scrollY>0)return;const dy=t.clientY-p.y,dx=t.clientX-p.x;if(dy<=0||Math.abs(dx)>Math.abs(dy)){setPullDistance(0);return}setPullDistance(Math.min(112,dy*.48))}
  const pullTouchEnd=()=>{if(!pullStart.current.active)return;pullStart.current.active=false;const refresh=pullDistance>=74;setPullDistance(0);if(refresh)setTimeout(()=>window.location.reload(),80)}
  const lightStep=dir=>{if(light?.galleryIndex==null)return;const next=Math.max(0,Math.min(gallery.length-1,light.galleryIndex+dir));if(next===light.galleryIndex)return;setLight({...gallery[next],galleryIndex:next})}
  const lightPointerDown=e=>{if(light?.galleryIndex==null)return;lightSwipe.current={active:true,x:e.clientX,y:e.clientY,pointerId:e.pointerId};e.currentTarget.setPointerCapture?.(e.pointerId)}
  const lightPointerUp=e=>{const p=lightSwipe.current;if(!p.active)return;p.active=false;const dx=e.clientX-p.x,dy=e.clientY-p.y;e.currentTarget.releasePointerCapture?.(e.pointerId);if(Math.abs(dx)>48&&Math.abs(dx)>Math.abs(dy)*1.15)lightStep(dx<0?1:-1)}
  useEffect(()=>{if(!light)return;const onKey=e=>{if(e.key==='Escape')setLight(null);if(light.galleryIndex!=null&&e.key==='ArrowLeft')lightStep(-1);if(light.galleryIndex!=null&&e.key==='ArrowRight')lightStep(1)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[light,gallery])
  async function guestSubmit(e){e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')||'').trim(),message=String(f.get('message')||'').trim();if(!name||!message){setGstatus('이름과 메시지를 입력해 주세요.');return}setGstatus('등록 중...');try{await edge('guestbook',{action:'create',name,message,website:''});e.currentTarget.reset();await loadComments(1);setGstatus('축하 메시지가 등록되었습니다 💜')}catch{setGstatus('등록에 실패했어요.')}}
  async function rsvpSubmit(e){e.preventDefault();const f=new FormData(e.currentTarget),payload={name:String(f.get('name')||'').trim(),side:String(f.get('side')||'other'),attendance:String(f.get('attendance')||'yes'),guests:Number(f.get('guests')||1),note:String(f.get('note')||'').trim(),website:''};if(!payload.name){setRstatus('성함을 입력해 주세요.');return}setRstatus('전송 중...');try{await edge('rsvp',payload);setRstatus('참석 여부가 전달되었습니다. 감사합니다 💜')}catch{setRstatus('전송에 실패했어요.')}}
  const menus=[['home','홈'],['story','전체'],['wedding','예식정보'],['gallery','사진첩'],['guestbook','방명록'],['gift','마음전하실곳']]
  return <div className="site-shell" ref={refs.home} onTouchStart={pullTouchStart} onTouchMove={pullTouchMove} onTouchEnd={pullTouchEnd} onTouchCancel={pullTouchEnd}><div className="phone-app">
    <div className={'pull-refresh '+(pullDistance>=74?'ready':'')} style={{transform:`translate(-50%, ${Math.max(-48,pullDistance-44)}px)`,opacity:pullDistance?1:0}} aria-hidden="true"><span className="pull-refresh-icon"><SvgIcon size={18}><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></SvgIcon></span><small>{pullDistance>=74?'놓으면 새로고침':'아래로 당겨 새로고침'}</small></div>
    <header className="app-header"><div className="brand-row"><button className="brand" onClick={()=>go('home')}><span className="play-mark"><span/></span><strong>{content.groom.replace(/^전/,'')} <b>♥</b> {content.bride.replace(/^최/,'')}</strong></button><div className="header-actions"><button className="icon-button" type="button" aria-label="알림"><BellIcon/></button><button className="icon-button" type="button" aria-label="검색"><SearchIcon/></button></div></div><nav className="category-rail">{menus.map(([k,l])=><button key={k} className={'chip '+(k==='home'?'home-chip ':'')+(active===k?'active':'')} onClick={()=>go(k)} aria-label={l}>{k==='home'?<CompassIcon/>:l}</button>)}</nav></header>
    <main>
      <section className="shorts-section section-anchor" ref={refs.story}><div className="youtube-heading"><h2>Shorts</h2><span>•••</span></div><div className="shorts-grid">{[[short1,content.short1_title,content.short1_text,'우리의 첫 만남 ♡'],[short2,content.short2_title,content.short2_text,'함께한 여행 ♡']].map(([src,title,text,ov])=><article className="short-card" key={title}><button className="photo-button short-image-wrap" onClick={()=>setLight({src,caption:title})}><img src={src}/><span className="short-overlay">{ov}</span></button><h2>{title}</h2><p>{text}</p></article>)}</div></section>
      <section className="main-video-card"><div className="video-thumb">{video?<video src={url(video)} controls playsInline preload="metadata" poster={hero}/>:<button className="photo-button main-photo-button" onClick={()=>setLight({src:hero,caption:content.main_title})}><img src={hero}/><span className="video-placeholder-label">Wedding Film</span></button>}</div><div className="video-info"><span className="channel-avatar"><span className="play-mark"><span/></span></span><div><h2>{content.main_title}</h2><p>{content.date} · 우리의 작은 무대에 초대합니다</p></div><span>•••</span></div></section>
      <section className="info-section section-anchor" ref={refs.wedding}><div className="youtube-heading"><h2>예식정보</h2><span>Premiere · {content.date}</span></div><div className="info-card"><div className="info-line"><span className="info-badge info-icon-badge" aria-hidden="true"><CalendarIcon/></span><div><strong>{content.date_display}</strong><p>{content.time}</p></div></div><div className="info-line"><span className="info-badge info-icon-badge" aria-hidden="true"><LocationIcon/></span><div><strong>{content.venue}</strong><p>{content.address||'상세 주소 추후 안내'}</p></div></div>{content.additional_info&&<p className="additional-info">{content.additional_info}</p>}{content.map_url?<a className="map-link" href={content.map_url} target="_blank" rel="noreferrer"><LocationIcon size={16}/><span>약도 보기</span></a>:<button className="map-status" disabled><LocationIcon size={16}/><span>약도 준비 중</span></button>}</div><article className="invitation-copy"><span className="copy-kicker">초대의 글</span><h2>{content.invitation_headline}</h2><p>{content.invitation_body}</p><div className="family-lines"><p>{content.groom_parents} <strong>{content.groom}</strong></p><p>{content.bride_parents} <strong>{content.bride}</strong></p></div></article></section>
      <section className="gallery-section section-anchor" ref={refs.gallery}><div className="youtube-heading"><h2>사진첩</h2><span>{gallery.length}개의 사진 · 옆으로 넘겨보세요</span></div><div className="gallery-carousel-wrap"><button type="button" className="gallery-arrow gallery-prev" aria-label="이전 사진" onClick={()=>galleryStep(-1)}><SvgIcon size={22}><path d="m15 18-6-6 6-6"/></SvgIcon></button><div className="gallery-rail" ref={galleryRail} onPointerDown={galleryPointerDown} onPointerMove={galleryPointerMove} onPointerUp={galleryPointerUp} onPointerCancel={galleryPointerUp}>{gallery.map((x,i)=><figure className="gallery-slide" key={x.src}><button className="photo-button gallery-photo-button" onClick={()=>{if(galleryDrag.current.moved){galleryDrag.current.moved=false;return}setLight({...x,galleryIndex:i})}}><img src={x.src} draggable="false"/></button><figcaption><span>{x.caption}</span><small>{i+1} / {gallery.length}</small></figcaption></figure>)}</div><button type="button" className="gallery-arrow gallery-next" aria-label="다음 사진" onClick={()=>galleryStep(1)}><SvgIcon size={22}><path d="m9 18 6-6-6-6"/></SvgIcon></button></div></section>
      <section className="guestbook-section section-anchor" ref={refs.guestbook}><div className="youtube-heading"><h2>방명록</h2><span>{total}개의 축하 댓글</span></div><form className="comment-composer" onSubmit={guestSubmit}><span className="comment-avatar">♡</span><div className="comment-inputs"><input name="name" maxLength="20" placeholder="이름"/><textarea name="message" maxLength="180" placeholder="두 사람에게 축하 메시지를 남겨주세요"/><div className="composer-actions"><span>{gstatus}</span><button>댓글</button></div></div></form><div className="comment-list">{comments.length?comments.map(x=><article className="comment" key={x.id}><span className="comment-avatar small">{x.name.slice(0,1)}</span><div><strong>{x.name}</strong><p>{x.message}</p><span className="comment-action">♡ 축하해요</span></div></article>):<p className="empty-comments">첫 번째 축하 메시지를 남겨주세요.</p>}</div>{pages>1&&<nav className="guestbook-pagination">{Array.from({length:pages},(_,i)=>i+1).map(p=><button key={p} className={p===page?'active':''} onClick={()=>loadComments(p)}>{p}</button>)}</nav>}</section>
      <section className="gift-section section-anchor" ref={refs.gift}><div className="youtube-heading"><h2>마음 전하실 곳</h2><span>신랑측 · 신부측</span></div><p className="gift-intro">참석이 어려우신 분들을 위해 계좌 안내 공간을 마련했습니다.</p>{[['신랑측 계좌',content.groom,content.groom_accounts],['신부측 계좌',content.bride,content.bride_accounts]].map(([l,n,v])=><details className="account-panel" key={l}><summary><span>{l}</span><strong>{n}</strong></summary><div className="account-body">{lines(v).length?lines(v).map(x=><p key={x}>{x}</p>):<span>계좌 정보는 추후 안내 예정입니다.</span>}</div></details>)}</section>
    </main>
    {showTop&&<button type="button" className="scroll-top-button" onClick={goTop} aria-label="맨 위로"><SvgIcon size={23}><path d="m6 15 6-6 6 6"/></SvgIcon><small>TOP</small></button>}
    <nav className="bottom-nav"><button className="bottom-item" onClick={()=>go('home')}><HomeIcon/><small>홈</small></button><button className="bottom-item" onClick={()=>go('story')}><ShortsIcon/><small>Shorts</small></button><button className="bottom-item create-item" onClick={()=>setRsvpOpen(true)} aria-label="참석 여부 전하기"><span className="plus-circle"><PlusIcon/></span></button><button className="bottom-item" onClick={()=>go('guestbook')}><SubscriptionsIcon/><small>구독</small></button><button className="bottom-item" onClick={()=>setProfileOpen(true)}><UserIcon/><small>내 페이지</small></button></nav>
  </div>
  {light&&<div className="lightbox" onClick={()=>setLight(null)}><button className="lightbox-close" aria-label="닫기"><SvgIcon size={25}><path d="M6 6l12 12M18 6 6 18"/></SvgIcon></button>{light.galleryIndex!=null&&<button className="lightbox-arrow lightbox-prev" aria-label="이전 사진" disabled={light.galleryIndex===0} onClick={e=>{e.stopPropagation();lightStep(-1)}}><SvgIcon size={28}><path d="m15 18-6-6 6-6"/></SvgIcon></button>}<figure className={light.galleryIndex!=null?'gallery-lightbox-figure':''} onClick={e=>e.stopPropagation()} onPointerDown={lightPointerDown} onPointerUp={lightPointerUp} onPointerCancel={lightPointerUp}><img src={light.src} draggable="false"/><figcaption>{light.caption}{light.galleryIndex!=null&&<small>{light.galleryIndex+1} / {gallery.length}</small>}</figcaption></figure>{light.galleryIndex!=null&&<button className="lightbox-arrow lightbox-next" aria-label="다음 사진" disabled={light.galleryIndex===gallery.length-1} onClick={e=>{e.stopPropagation();lightStep(1)}}><SvgIcon size={28}><path d="m9 18 6-6-6-6"/></SvgIcon></button>}</div>}
  {rsvpOpen&&<div className="modal-backdrop" onClick={()=>setRsvpOpen(false)}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-head"><div><span>+ 만들기</span><h2>참석 여부 전하기</h2></div><button onClick={()=>setRsvpOpen(false)}>×</button></div><form className="rsvp-form" onSubmit={rsvpSubmit}><label>성함<input name="name" maxLength="20"/></label><label>어느 쪽 하객이신가요?<select name="side"><option value="groom">신랑측</option><option value="bride">신부측</option><option value="other">기타</option></select></label><fieldset><legend>참석 여부</legend><div className="radio-row"><label><input type="radio" name="attendance" value="yes" defaultChecked/>참석</label><label><input type="radio" name="attendance" value="maybe"/>미정</label><label><input type="radio" name="attendance" value="no"/>불참</label></div></fieldset><label>총 참석 인원<select name="guests" defaultValue="1">{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><label>남기실 말<textarea name="note" maxLength="200"/></label><button className="submit-rsvp">전달하기</button>{rstatus&&<p className="form-status">{rstatus}</p>}</form></section></div>}
  {profileOpen&&<div className="modal-backdrop" onClick={()=>setProfileOpen(false)}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-head"><div><span>내 페이지</span><h2>{content.groom.replace(/^전/,'')} ♥ {content.bride.replace(/^최/,'')}</h2></div><button onClick={()=>setProfileOpen(false)}>×</button></div><div className="profile-hero"><img src={hero}/><div><strong>{content.date_display}</strong><p>두 사람이 하나의 팀이 되는 날</p></div></div></section></div>}
  </div>
}
