import React,{useEffect,useMemo,useRef,useState} from 'react'
import {edge,publicMedia,supabase} from './supabase'

const FALLBACK={groom:'전범수',bride:'최서영',date:'2027-12-11',date_display:'2027년 12월 11일 토요일',time:'오후 3시',venue:'예식 장소 추후 안내',address:'',map_url:'',groom_parents:'전용섭 · 손미연의 장남',bride_parents:'최영민 · 배은희의 장녀',invitation_headline:'결혼은 마라톤? 아니요,\n저희는 릴레이로 뛰려 합니다.',invitation_body:'때론 달리고, 때론 쉬고,\n서로의 바통을 꼭 잡고 달릴 거예요.\n\n완벽하지 않아도 괜찮아요,\n같이 웃고 울며 성장할 테니까요.\n\n그 시작점에 여러분의 따뜻한 응원이 큰 힘이 됩니다.\n지켜봐 주세요, 그리고 함께 축하해 주세요!\n우리의 작은 무대에 여러분을 초대합니다.',additional_info:'',groom_accounts:'',bride_accounts:'',short1_title:'게임에서 시작된 우리',short1_text:'친구의 친구로 만나, 어느새 가장 가까운 사이가 됐어요 💜',short2_title:'함께라서 기대되는 내일',short2_text:'경주에서 오사카까지, 우리의 추억은 계속 쌓이는 중 💜',main_title:'전범수 ♥ 최서영 모바일 청첩장'}
const defaults={hero:publicMedia('defaults/hero.png'),short1:publicMedia('defaults/short-first.png'),short2:publicMedia('defaults/short-gyeongju.png'),osaka:publicMedia('defaults/short-osaka.png')}
const url=m=>m?publicMedia(m.object_path):null
const lines=v=>(v||'').split('\n').map(x=>x.trim()).filter(Boolean)

export default function App(){
  const [content,setContent]=useState(FALLBACK),[media,setMedia]=useState([]),[comments,setComments]=useState([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0),[light,setLight]=useState(null),[rsvpOpen,setRsvpOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false),[gstatus,setGstatus]=useState(''),[rstatus,setRstatus]=useState('')
  const refs={home:useRef(null),story:useRef(null),wedding:useRef(null),gallery:useRef(null),guestbook:useRef(null),gift:useRef(null)}
  const [active,setActive]=useState('home')
  useEffect(()=>{(async()=>{const [{data:c},{data:m}]=await Promise.all([supabase.from('wedding_content').select('*').eq('id',1).single(),supabase.from('wedding_media').select('*').order('created_at',{ascending:false})]);if(c)setContent(c);if(m)setMedia(m);await loadComments(1)})()},[])
  async function loadComments(p){const from=(p-1)*5;const {data,count}=await supabase.from('guestbook').select('id,name,message,created_at,updated_at',{count:'exact'}).order('created_at',{ascending:false}).range(from,from+4);setComments(data||[]);setTotal(count||0);setPage(p);setPages(Math.max(1,Math.ceil((count||0)/5)))}
  const role=r=>media.find(x=>x.role===r)
  const hero=url(role('hero'))||defaults.hero,short1=url(role('short1'))||defaults.short1,short2=url(role('short2'))||defaults.short2,video=role('video')
  const gallery=useMemo(()=>{const g=media.filter(x=>x.role==='gallery');return g.length?g.map(x=>({src:url(x),caption:x.caption||'우리의 사진'})):[{src:hero,caption:'2027 · 우리 결혼합니다'},{src:short1,caption:'우리의 시작'},{src:short2,caption:'경주'},{src:defaults.osaka,caption:'오사카'}]},[media,hero,short1,short2])
  const go=k=>{setActive(k);refs[k].current?.scrollIntoView({behavior:'smooth',block:'start'})}
  async function guestSubmit(e){e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')||'').trim(),message=String(f.get('message')||'').trim();if(!name||!message){setGstatus('이름과 메시지를 입력해 주세요.');return}setGstatus('등록 중...');try{await edge('guestbook',{action:'create',name,message,website:''});e.currentTarget.reset();await loadComments(1);setGstatus('축하 메시지가 등록되었습니다 💜')}catch{setGstatus('등록에 실패했어요.')}}
  async function rsvpSubmit(e){e.preventDefault();const f=new FormData(e.currentTarget),payload={name:String(f.get('name')||'').trim(),side:String(f.get('side')||'other'),attendance:String(f.get('attendance')||'yes'),guests:Number(f.get('guests')||1),note:String(f.get('note')||'').trim(),website:''};if(!payload.name){setRstatus('성함을 입력해 주세요.');return}setRstatus('전송 중...');try{await edge('rsvp',payload);setRstatus('참석 여부가 전달되었습니다. 감사합니다 💜')}catch{setRstatus('전송에 실패했어요.')}}
  const menus=[['home','홈'],['story','전체'],['wedding','예식정보'],['gallery','사진첩'],['guestbook','방명록'],['gift','마음전하실곳']]
  return <div className="site-shell" ref={refs.home}><div className="phone-app">
    <header className="app-header"><div className="brand-row"><button className="brand" onClick={()=>go('home')}><span className="play-mark"><span/></span><strong>{content.groom.replace(/^전/,'')} <b>♥</b> {content.bride.replace(/^최/,'')}</strong></button><div className="header-actions">♡ ⌕</div></div><nav className="category-rail">{menus.map(([k,l])=><button key={k} className={'chip '+(active===k?'active':'')} onClick={()=>go(k)}>{k==='home'?'⌂':l}</button>)}</nav></header>
    <main>
      <section className="shorts-section section-anchor" ref={refs.story}><div className="youtube-heading"><h2>Shorts</h2><span>•••</span></div><div className="shorts-grid">{[[short1,content.short1_title,content.short1_text,'우리의 첫 만남 ♡'],[short2,content.short2_title,content.short2_text,'함께한 여행 ♡']].map(([src,title,text,ov])=><article className="short-card" key={title}><button className="photo-button short-image-wrap" onClick={()=>setLight({src,caption:title})}><img src={src}/><span className="short-overlay">{ov}</span></button><h2>{title}</h2><p>{text}</p></article>)}</div></section>
      <section className="main-video-card"><div className="video-thumb">{video?<video src={url(video)} controls playsInline preload="metadata" poster={hero}/>:<button className="photo-button main-photo-button" onClick={()=>setLight({src:hero,caption:content.main_title})}><img src={hero}/><span className="video-placeholder-label">Wedding Film</span></button>}</div><div className="video-info"><span className="channel-avatar"><span className="play-mark"><span/></span></span><div><h2>{content.main_title}</h2><p>{content.date} · 우리의 작은 무대에 초대합니다</p></div><span>•••</span></div></section>
      <section className="info-section section-anchor" ref={refs.wedding}><div className="youtube-heading"><h2>예식정보</h2><span>Premiere · {content.date}</span></div><div className="info-card"><div className="info-line"><span className="info-badge">11</span><div><strong>{content.date_display}</strong><p>{content.time}</p></div></div><div className="info-line"><span className="info-badge">⌖</span><div><strong>{content.venue}</strong><p>{content.address||'상세 주소 추후 안내'}</p></div></div>{content.additional_info&&<p className="additional-info">{content.additional_info}</p>}{content.map_url?<a className="map-link" href={content.map_url} target="_blank" rel="noreferrer">약도 보기</a>:<button className="map-status" disabled>약도 준비 중</button>}</div><article className="invitation-copy"><span className="copy-kicker">초대의 글</span><h2>{content.invitation_headline}</h2><p>{content.invitation_body}</p><div className="family-lines"><p>{content.groom_parents} <strong>{content.groom}</strong></p><p>{content.bride_parents} <strong>{content.bride}</strong></p></div></article></section>
      <section className="gallery-section section-anchor" ref={refs.gallery}><div className="youtube-heading"><h2>사진첩</h2><span>{gallery.length}개의 사진</span></div><div className="gallery-grid">{gallery.map((x,i)=><figure className={'gallery-item '+(i===0?'wide':'')} key={x.src}><button className="photo-button" onClick={()=>setLight(x)}><img src={x.src}/></button><figcaption>{x.caption}</figcaption></figure>)}</div></section>
      <section className="guestbook-section section-anchor" ref={refs.guestbook}><div className="youtube-heading"><h2>방명록</h2><span>{total}개의 축하 댓글</span></div><form className="comment-composer" onSubmit={guestSubmit}><span className="comment-avatar">♡</span><div className="comment-inputs"><input name="name" maxLength="20" placeholder="이름"/><textarea name="message" maxLength="180" placeholder="두 사람에게 축하 메시지를 남겨주세요"/><div className="composer-actions"><span>{gstatus}</span><button>댓글</button></div></div></form><div className="comment-list">{comments.length?comments.map(x=><article className="comment" key={x.id}><span className="comment-avatar small">{x.name.slice(0,1)}</span><div><strong>{x.name}</strong><p>{x.message}</p><span className="comment-action">♡ 축하해요</span></div></article>):<p className="empty-comments">첫 번째 축하 메시지를 남겨주세요.</p>}</div>{pages>1&&<nav className="guestbook-pagination">{Array.from({length:pages},(_,i)=>i+1).map(p=><button key={p} className={p===page?'active':''} onClick={()=>loadComments(p)}>{p}</button>)}</nav>}</section>
      <section className="gift-section section-anchor" ref={refs.gift}><div className="youtube-heading"><h2>마음 전하실 곳</h2><span>신랑측 · 신부측</span></div><p className="gift-intro">참석이 어려우신 분들을 위해 계좌 안내 공간을 마련했습니다.</p>{[['신랑측 계좌',content.groom,content.groom_accounts],['신부측 계좌',content.bride,content.bride_accounts]].map(([l,n,v])=><details className="account-panel" key={l}><summary><span>{l}</span><strong>{n}</strong></summary><div className="account-body">{lines(v).length?lines(v).map(x=><p key={x}>{x}</p>):<span>계좌 정보는 추후 안내 예정입니다.</span>}</div></details>)}</section>
    </main>
    <nav className="bottom-nav"><button onClick={()=>go('home')}><span>⌂</span><small>홈</small></button><button onClick={()=>go('story')}><span>▰</span><small>Shorts</small></button><button className="create-item" onClick={()=>setRsvpOpen(true)}><span className="plus-circle">+</span></button><button onClick={()=>go('guestbook')}><span>▣</span><small>구독</small></button><button onClick={()=>setProfileOpen(true)}><span>◯</span><small>내 페이지</small></button></nav>
  </div>
  {light&&<div className="lightbox" onClick={()=>setLight(null)}><button>×</button><figure onClick={e=>e.stopPropagation()}><img src={light.src}/><figcaption>{light.caption}</figcaption></figure></div>}
  {rsvpOpen&&<div className="modal-backdrop" onClick={()=>setRsvpOpen(false)}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-head"><div><span>+ 만들기</span><h2>참석 여부 전하기</h2></div><button onClick={()=>setRsvpOpen(false)}>×</button></div><form className="rsvp-form" onSubmit={rsvpSubmit}><label>성함<input name="name" maxLength="20"/></label><label>어느 쪽 하객이신가요?<select name="side"><option value="groom">신랑측</option><option value="bride">신부측</option><option value="other">기타</option></select></label><fieldset><legend>참석 여부</legend><div className="radio-row"><label><input type="radio" name="attendance" value="yes" defaultChecked/>참석</label><label><input type="radio" name="attendance" value="maybe"/>미정</label><label><input type="radio" name="attendance" value="no"/>불참</label></div></fieldset><label>총 참석 인원<select name="guests" defaultValue="1">{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><label>남기실 말<textarea name="note" maxLength="200"/></label><button className="submit-rsvp">전달하기</button>{rstatus&&<p className="form-status">{rstatus}</p>}</form></section></div>}
  {profileOpen&&<div className="modal-backdrop" onClick={()=>setProfileOpen(false)}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-head"><div><span>내 페이지</span><h2>{content.groom.replace(/^전/,'')} ♥ {content.bride.replace(/^최/,'')}</h2></div><button onClick={()=>setProfileOpen(false)}>×</button></div><div className="profile-hero"><img src={hero}/><div><strong>{content.date_display}</strong><p>두 사람이 하나의 팀이 되는 날</p></div></div></section></div>}
  </div>
}
